import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header'
import Footer from './components/footer'
import { PostsProvider } from './providers/postsProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en" className='w-full min-h-full h-full overflow-hidden'>
      <body className='h-full flex flex-col'>
        <Header />
        <section className='overflow-scroll h-full pt-[60px]  bg-slate-600'>
          {children}
        </section>
      </body>
    </html>

  )
}
